// Code generated by "stringer -type=Mode"; DO NOT EDIT.

package rigcontrol

import "fmt"

const (
	_Mode_name_0 = "ModeLSBModeUSBModeCWModeCWRModeAM"
	_Mode_name_1 = "ModeWFM"
	_Mode_name_2 = "ModeFM"
	_Mode_name_3 = "ModeDIG"
	_Mode_name_4 = "ModePKT"
	_Mode_name_5 = "ModeCWN"
	_Mode_name_6 = "ModeNFM"
)

var (
	_Mode_index_0 = [...]uint8{0, 7, 14, 20, 27, 33}
	_Mode_index_1 = [...]uint8{0, 7}
	_Mode_index_2 = [...]uint8{0, 6}
	_Mode_index_3 = [...]uint8{0, 7}
	_Mode_index_4 = [...]uint8{0, 7}
	_Mode_index_5 = [...]uint8{0, 7}
	_Mode_index_6 = [...]uint8{0, 7}
)

func (i Mode) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _Mode_name_0[_Mode_index_0[i]:_Mode_index_0[i+1]]
	case i == 6:
		return _Mode_name_1
	case i == 8:
		return _Mode_name_2
	case i == 10:
		return _Mode_name_3
	case i == 12:
		return _Mode_name_4
	case i == 130:
		return _Mode_name_5
	case i == 136:
		return _Mode_name_6
	default:
		return fmt.Sprintf("Mode(%d)", i)
	}
}
