package adif

import (
	"fmt"
	"io"
	"strings"
)

// Identifier is an ADIF record type
type Identifier string

// list of the known record types
const (
	AdifVersion      Identifier = "adif_ver"
	CreatedTimestamp Identifier = "created_timestamp"
	ProgramID        Identifier = "programid"
	ProgramVersion   Identifier = "programversion"
	Userdef          Identifier = "userdef"

	Address                   Identifier = "address"
	AddressInternational      Identifier = "address_intl"
	Age                       Identifier = "age"
	AIndex                    Identifier = "a_index"
	AntennaAz                 Identifier = "ant_az"
	AntennaEl                 Identifier = "ant_el"
	AntennaPath               Identifier = "ant_path"
	ARRLSection               Identifier = "arrl_sect"
	AwardSubmitted            Identifier = "award_submitted"
	AwardGranted              Identifier = "award_granted"
	ABand                     Identifier = "band"
	BandRX                    Identifier = "band_rx"
	Call                      Identifier = "call"
	Check                     Identifier = "check"
	Class                     Identifier = "class"
	ClublogQSOUploadDate      Identifier = "clublog_qso_upload_date"
	ClublogQSOUploadStatus    Identifier = "clublog_qso_upload_status"
	County                    Identifier = "cnty"
	Comment                   Identifier = "comment"
	CommentInternational      Identifier = "comment_intl"
	Continent                 Identifier = "cont"
	ContactedOperator         Identifier = "contacted_op"
	ContestId                 Identifier = "contest_id"
	Country                   Identifier = "country"
	CountryInternational      Identifier = "country_intnl"
	CQZone                    Identifier = "cqz"
	CreditSubmitted           Identifier = "credit_submitted"
	CreditGranted             Identifier = "credit_granted"
	DARCDOC                   Identifier = "darc_doc"
	Distance                  Identifier = "distance"
	DXCC                      Identifier = "dxcc"
	Email                     Identifier = "email"
	EQCall                    Identifier = "eq_call"
	EQSLReceivedDate          Identifier = "eqsl_qslrdate"
	EQSLSentDate              Identifier = "eqsl_qslsdate"
	EQSLReceived              Identifier = "eqsl_qsl_rcvd"
	EQSLSent                  Identifier = "eqsl_qsl_sent"
	FISTS                     Identifier = "fists"
	FISTSCountryCode          Identifier = "fists_cc"
	ForceInit                 Identifier = "force_init"
	Frequency                 Identifier = "freq"
	FrequencyRX               Identifier = "freq_rx"
	GridSquare                Identifier = "gridsquare"
	GuestOperator             Identifier = "guest_op"
	HRDLOGUploadDate          Identifier = "hrdlog_qso_upload_date"
	HRDLOGUploadStatus        Identifier = "HRDLOG_QSO_UPLOAD_STATUS"
	IOTA                      Identifier = "iota"
	IOTAId                    Identifier = "iota_island_id"
	ITUZone                   Identifier = "ituz"
	KIndex                    Identifier = "k_index"
	Latitude                  Identifier = "lat"
	Longitude                 Identifier = "lon"
	LOTWReceivedDate          Identifier = "lotw_qslrdate"
	LOTWSentDate              Identifier = "lotw_qslsdate"
	LOTWReceived              Identifier = "lotw_qsl_rcvd"
	LOTWSent                  Identifier = "lotw_qsl_sent"
	MaxBursts                 Identifier = "max_bursts"
	AMode                     Identifier = "mode"
	MSShower                  Identifier = "ms_shower"
	MyAntenna                 Identifier = "my_antenna"
	MyAntennaInternational    Identifier = "my_antenna_intl"
	MyCity                    Identifier = "my_city"
	MyCityInternational       Identifier = "my_city_intl"
	MyCounty                  Identifier = "my_cnty"
	MyCountry                 Identifier = "my_country"
	MyCountryInternational    Identifier = "my_country_intl"
	MyCQZone                  Identifier = "my_cq_zone"
	MyDXCC                    Identifier = "my_dxcc"
	MyFISTS                   Identifier = "my_fists"
	MyGridSquare              Identifier = "my_gridsquare"
	MyIOTA                    Identifier = "my_iota"
	MyIOTAId                  Identifier = "my_iota_island_id"
	MyITUZone                 Identifier = "my_itu_zone"
	MyLatitude                Identifier = "my_lat"
	MyLongitude               Identifier = "my_lon"
	MyName                    Identifier = "my_name"
	MyNameInternational       Identifier = "my_name_intl"
	MyPostalCode              Identifier = "my_postal_code"
	MyPostalCodeInternational Identifier = "my_postal_code_intl"
	MyRig                     Identifier = "my_rig"
	MyRigInternational        Identifier = "my_rig_intl"
	MySIG                     Identifier = "my_sig"
	MySIGInternational        Identifier = "my_sig_intl"
	MySIGInfo                 Identifier = "my_sig_info"
	MySIGInfoInternational    Identifier = "my_sig_info_intl"
	MySOTARef                 Identifier = "my_sota_ref"
	MyState                   Identifier = "my_state"
	MyStreet                  Identifier = "my_street"
	MyStreetInternational     Identifier = "my_street_intl"
	MyUSACACounties           Identifier = "my_usaca_counties"
	MyVUCCGrids               Identifier = "my_vucc_grids"
	Name                      Identifier = "name"
	NameInternational         Identifier = "name_intl"
	Notes                     Identifier = "notes"
	NotesInternational        Identifier = "notes_intl"
	NumberBursts              Identifier = "nr_bursts"
	NumberPings               Identifier = "nr_pings"
	Operator                  Identifier = "operator"
	OwnerCallsign             Identifier = "owner_callsign"
	PFX                       Identifier = "pfx"
	Precedence                Identifier = "precedence"
	PropMode                  Identifier = "prop_mode"
	PublicKey                 Identifier = "public_key"
	QRZCOMUploadDate          Identifier = "qrzcom_qso_upload_date"
	QRZCOMUploadStatus        Identifier = "qrzcom_qso_upload_status"
	QSLMsg                    Identifier = "qslmsg"
	QSLMsgInternational       Identifier = "qslmsg_intl"
	QSLReceivedDate           Identifier = "qslrdate"
	QSLSentDate               Identifier = "qslsdate"
	QSLReceived               Identifier = "qsl_rcvd"
	QSLReceivedVia            Identifier = "qsl_rcvd_via"
	QSLSent                   Identifier = "qsl_sent"
	QSLSentVia                Identifier = "qsl_sent_via"
	QSLVia                    Identifier = "qsl_via"
	QSOComplete               Identifier = "qso_complete"
	QSODateStart              Identifier = "qso_date"
	QSODateEnd                Identifier = "qso_date_off"
	QSORandom                 Identifier = "qso_random"
	QTH                       Identifier = "qth"
	QTHInternational          Identifier = "qth_intl"
	Region                    Identifier = "region"
	Rig                       Identifier = "rig"
	RigInternational          Identifier = "rig_intl"
	RSTReceived               Identifier = "rst_rcvd"
	RSTSent                   Identifier = "rst_sent"
	RXPower                   Identifier = "rx_pwr"
	SatelliteMode             Identifier = "sat_mode"
	SatelliteName             Identifier = "sat_name"
	SFI                       Identifier = "sfi"
	SIG                       Identifier = "sig"
	SIGInternational          Identifier = "sig_intl"
	SIGInfo                   Identifier = "sig_info"
	SIGInfoInternational      Identifier = "sig_info_intl"
	SilentKey                 Identifier = "silent_key"
	SKCC                      Identifier = "skcc"
	SOTA_Reference            Identifier = "sota_ref"
	SRX                       Identifier = "srx"
	SRX_String                Identifier = "srx_string"
	State                     Identifier = "state"
	StationCallsign           Identifier = "station_callsign"
	STX                       Identifier = "stx"
	STXString                 Identifier = "stx_string"
	Submode                   Identifier = "submode"
	SWL                       Identifier = "swl"
	TenTen                    Identifier = "ten_ten"
	TimeOff                   Identifier = "time_off"
	TimeOn                    Identifier = "time_on"
	TXPower                   Identifier = "tx_pwr"
	UKSMG                     Identifier = "uksmg"
	USACACounties             Identifier = "usaca_counties"
	VE_Prov                   Identifier = "ve_prov"
	VUCC_Grids                Identifier = "vucc_grids"
	Website                   Identifier = "web"
)

type Field struct {
	Name   Identifier
	Value  string
	Length int
	Type   string
}

func (f *Field) Normalize() {
	f.Name = Identifier(strings.ToLower(string(f.Name)))
	f.Length = len(f.Value)
}

func (f Field) Write(w io.Writer) {
	if f.Type == "" {
		fmt.Fprintf(w, "<%s:%d>%s\n", f.Name, f.Length, f.Value)
	} else {
		fmt.Fprintf(w, "<%s:%d:%s>%s\n", f.Name, f.Length, f.Type, f.Value)
	}
}
func (r Field) String() string {
	return fmt.Sprintf("{%s %s}", r.Name, r.Value)
}
