// Code generated by "stringer -type=Token"; DO NOT EDIT.

package adif

import "fmt"

const _Token_name = "tokenErrortokenLexErrortokenEOFtokenEOHtokenEORtokenColontokenNLtokenLAngletokenRAngletokenOther"

var _Token_index = [...]uint8{0, 10, 23, 31, 39, 47, 57, 64, 75, 86, 96}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
