// Code generated by "stringer -type=MessageCode"; DO NOT EDIT.

package wsjtx

import "fmt"

const _MessageCode_name = "MessageHeartbeatMessageStatusMessageDecodeMessageClearMessageReplyMessageQSOLoggedMessageCloseMessageReplayMessageHaltTXMessageFreeTextMessageWSPRDecode"

var _MessageCode_index = [...]uint8{0, 16, 29, 42, 54, 66, 82, 94, 107, 120, 135, 152}

func (i MessageCode) String() string {
	if i >= MessageCode(len(_MessageCode_index)-1) {
		return fmt.Sprintf("MessageCode(%d)", i)
	}
	return _MessageCode_name[_MessageCode_index[i]:_MessageCode_index[i+1]]
}
